services:
  - type: web
    name: dental-clinic-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npx prisma db push --accept-data-loss && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://dental-clinic-jade.vercel.app
      - key: SUPABASE_URL
        value: https://dgtmcdryhpbjhuiofsdc.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_PnhCIjsPL3MHlewv3Rk-XA_SvTMtaD8
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        value: https://dgtmcdryhpbjhuiofsdc.supabase.co/auth/v1/.well-known/jwks.json
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        value: sheets-sync@dental-clinic-sync.iam.gserviceaccount.com
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
